project:
  type: website
  output-dir: docs
  
execute: 
  freeze: auto

website:
  title: "CaSE Laboratory"
  navbar:
    left:
      - text: About the Lab
        menu: 
          - text: Lab Mission
            href: mission.qmd
          - text: Meet Us
            href: people.qmd
      - text: Publications
        href: publications.qmd
      - text: Resources
        menu:
          - text: For Scientists
            href: sciresources.qmd
          - text: For Students
            href: opportunities.qmd
          - text: For Families
            href: famresources.qmd
      - text: Participate
        href: participate.qmd
      - text: Contact
        href: contact.qmd
      - text: News
        href: news.qmd

  page-footer: "This website was created in R with Quarto. <br />Copyright 2025 &copy; Helen Long"
  
format:
  html:
    theme: brite
    css: styles.css
    toc: true

editor: source

