project:
  type: website
  output-dir: docs
  
execute: 
  freeze: auto

website:
  title: "CaSE Laboratory"
  navbar:
    left:
      - text: Home      
        href: index.qmd
      - text: About
        menu: 
          - text: Mission
            href: mission.qmd
          - text: People
            href: people.qmd
          - text: News
            href: news.qmd
          - text: Contact
            href: contact.qmd
      - text: Research
        menu:
          - text: Publications
            href: publications.qmd
      - text: Students
        menu:
          - text: Lab Opportunities
            href: opportunities.qmd
          - text: Teaching
            href: courses.qmd
      - text: Resources
        menu:
          - text: For Families
            href: famresources.qmd
          - text: For Scientists
            href: sciresources.qmd
      - text: Participants
        menu:
          - text: Participate
            href: participate.qmd
          - text: Find Us
            href: contact.qmd

  page-footer: "This website was created in R with Quarto. <br />Copyright 2025 &copy; Helen Long"
  
format:
  html:
    theme: brite
    css: styles.css
    toc: true

editor: source

