---
title: "Preterm and full-term infant vocalization and the origin of language"
type: "article"
author: "Oller, Caskey, Yoo, Bene, Jhang, Lee, Bowman, Long, Buder, & Vohr"
year: "2019"
publication: "Scientific Reports"
doi: "https://doi.org/10.1038/s41598-019-51352-0"
oa: "https://doi.org/10.1038/s41598-019-51352-0"
toc: false
categories:
  - neurodevelopment
  - infant 
  - vocal development
---

```{=html}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="../../index.html">Home</a></li>
    <li class="breadcrumb-item"><a href="../../publications.html">Publications</a></li>
  </ol>
</nav>
```


> Oller, D. K., Caskey, M., Yoo, H., Bene, E. R., Jhang, Y., Lee, C.-C., Bowman, D. D., Long, H. L., Buder, E. H., & Vohr, B. (2019). Preterm and full-term infant vocalization and the origin of language. *Scientific Reports, 9*(1), 14734. https://doi.org/10.1038/s41598-019-51352-0

# Abstract

How did vocal language originate? Before trying to determine how referential vocabulary or syntax may have arisen, it is critical to explain how ancient hominins began to produce vocalization flexibly, without binding to emotions or functions. A crucial factor in the vocal communicative split of hominins from the ape background may thus have been copious, functionally flexible vocalization, starting in infancy and continuing throughout life, long before there were more advanced linguistic features such as referential vocabulary. 2--3 month-old modern human infants produce "protophones", including at least three types of functionally flexible non-cry precursors to speech rarely reported in other ape infants. But how early in life do protophones actually appear? We report that the most common protophone types emerge abundantly as early as vocalization can be observed in infancy, in preterm infants still in neonatal intensive care. Contrary to the expectation that cries are the predominant vocalizations of infancy, our all-day recordings showed that protophones occurred far more frequently than cries in both preterm and full-term infants. Protophones were not limited to interactive circumstances, but also occurred at high rates when infants were alone, indicating an endogenous inclination to vocalize exploratorily, perhaps the most fundamental capacity underlying vocal language.
