---
title: "Reliability of listener judgments of infant vocal imitations"
title-block: none
type: "article"
author: "Long, Oller & Bowman"
year: "2019"
publication: "Frontiers in Psychology"
doi: "https://doi.org/10.3389/fpsyg.2019.01340"
oa: "https://doi.org/10.3389/fpsyg.2019.01340"
materials: "https://osf.io/h7w9q/"
toc: false
categories:
  - imitation
  - infant 
  - vocal development
---

```{=html}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="../../index.html">Home</a></li>
    <li class="breadcrumb-item"><a href="../../publications.html">Publications</a></li>
  </ol>
</nav>
```

## Citation (APA 7)

> Long, H. L., Oller, D. K., & Bowman, D. D. (2019). Reliability of listener judgments of infant vocal imitation. *Frontiers in Psychology, 10,* 1340. https://doi.org/10.3389/fpsyg.2019.01340

## Abstract

There are many theories surrounding infant imitation; however, there is no research to our knowledge evaluating the reliability of listener perception of vocal imitation in prelinguistic infants. This paper evaluates intra- and inter-rater judgments on the degree of "imitativeness" in utterances of infants below 12 months of age. 18 listeners were presented audio segments selected from naturalistic recordings to represent in each case a parent vocal model followed by an infant utterance ranging from low to high degrees of imitativeness. The naturalistic data suggested vocal imitation occurred rarely across the first year, but strong intra- and inter-rater correlations were found for judgments of imitativeness. Our results suggest salience of the infant's vocal imitation despite its rare occurrence as well as active perception by listeners of the imitative signal. We discuss infant vocal imitation as a potential signal of well-being as perceived by caregivers.
