---
title: "Early vocal development in tuberous sclerosis complex"
type: "article"
author: "Gipson, Ramsay, Ellison, Bene, Long, & Oller"
year: "2021"
publication: "Pediatric Neurology"
doi: "https://doi.org/10.1016/j.pediatrneurol.2021.08.009"
pubmed: "https://pmc.ncbi.nlm.nih.gov/articles/PMC8557126/"
toc: false
categories:
  - tuberous sclerosis
  - infant 
  - vocal development
---

```{=html}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="../../index.html">Home</a></li>
    <li class="breadcrumb-item"><a href="../../publications.html">Publications</a></li>
  </ol>
</nav>
```


> Gipson, T. T., Ramsay, G., Ellison, E. E., Bene, E. R., Long, H. L., & Oller, D. K. (2021). Early vocal development in tuberous sclerosis complex. *Pediatric Neurology*, *125*, 48--52. <https://doi.org/10.1016/j.pediatrneurol.2021.08.009>

# Abstract

Objective: To assess early vocalizations as precursors to speech in audio-video recordings of infants with Tuberous Sclerosis Complex (TSC).

Methods: We randomly selected 40 infants with TSC from the TSC Autism Center of Excellence Research Network (TACERN) dataset. Using human observers, we analyzed 74 audio-video recordings within a flexible software-based coding environment. During the recordings, infants were engaged in developmental testing. We determined: syllables per minute (volubility), the number of consonant-vowel combinations, such as 'ba' (canonical babbling), the canonical babbling ratio (CBR) (canonical syllables/total syllables) and compared the data with 2 groups of typically developing (TD) infants. One comparison group's data had come from a laboratory setting, while the other's had come from all-day LENA (Language Environment Analysis) recordings at home.

Results: Compared to TD infants in laboratory and all-day LENA recordings, entry into the canonical babbling stage was delayed in the majority of infants with TSC, and the canonical babbling ratio was low (TD mean = .346, SE = .19; TSC mean = .117, SE = .023). Volubility level in infants with TSC was less than half that of TD infants (TD mean = 9.82, SE = 5.78; TSC mean = 3.99, SE = 2.16).

Conclusions: Entry into the canonical stage and other precursors of speech development were delayed in infants with TSC and may signal poor language and developmental outcomes. Future studies are planned to assess prediction of language and developmental outcomes using these measures in a larger sample and in more precisely comparable recording circumstances.
