---
title: "Functional communication abilities in youth with cerebral palsy: Association with impairment profiles and school-based therapy goals"
type: "article"
author: "Koopmans, Sakash, Soriano, Long, & Hustad"
year: "2021"
publication: "Language, Speech, and Hearing Services in Schools"
doi: "https://doi.org/10.1044/2021_LSHSS-21-00064"
pubmed: "https://pubmed.ncbi.nlm.nih.gov/34767477/"
toc: false
categories:
  - communication
  - cerebral palsy
---

```{=html}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="../../index.html">Home</a></li>
    <li class="breadcrumb-item"><a href="../../publications.html">Publications</a></li>
  </ol>
</nav>
```


> Koopmans, C., Sakash, A., Soriano, J., Long, H. L., & Hustad, K. C. (2021). Functional communication abilities in youth with cerebral palsy: Association with impairment profiles and school-based therapy goals. *Language, Speech, and Hearing Services in Schools*, 1--16. <https://doi.org/10.1044/2021_LSHSS-21-00064>

# Abstract

Purpose: The aim of this study was to examine the relationship between functional communication skills, underlying speech, language, and cognitive impairments and school-based speech pathology services in students with cerebral palsy (CP).

Method: Thirty-five participants with CP who had Individualized Education Programs (IEPs) were classified according to the Communication Function Classification System (CFCS). Participants completed laboratory assessments of speech, receptive language, executive functioning, and nonverbal cognition. Each participant's speech and language IEP goals were coded into treatment units and then categorized into seven, mutually exclusive target goal areas. Nonparametric analyses were employed to examine differences among CFCS groups in the number of deficit areas and the number of goal areas from the IEP. Descriptive analyses were used to evaluate the extent to which deficit and goal areas in the IEP co-occurred by CFCS level.

Results: Those in more involved CFCS levels demonstrated more severe speech, receptive language, and cognitive impairments. However, there were no significant differences in the number of deficit areas across CFCS groups. Regardless of CFCS level, there were no differences in the number of treatment goals specified in the IEP. Literacy was the only goal area addressed across all CFCS levels. Those in the most involved CFCS levels had augmentative and alternative communication (AAC) goals, but those with more moderate restrictions in functional communication who also had markedly reduced speech intelligibility did not typically have speech or AAC goals.

Interpretation: Individuals with CP across CFCS levels demonstrate variability in underlying deficit profiles, suggesting that measures of both functional communication and of underlying deficits are necessary to provide a complete picture of communication needs. Literacy goals were common across all CFCS levels, but AAC goals were limited to the most severely involved individuals, suggesting that continuing education may be necessary to support speech-language pathologists in developing treatments involving the integration of AAC and speech to foster functional communication at school.
