---
title: "Protophones, the precursors to speech, dominate the human infant vocal landscape"
type: "article"
author: "Oller, Ramsay, Bene, Long, & Griebel"
year: "2021"
publication: "Philosophical Transactions of the Royal Society B: Biological Sciences"
doi: "https://doi.org/10.1098/rstb.2020.0255"
oa: "https://doi.org/10.1098/rstb.2020.0255"
toc: false
categories:
  - infant 
  - vocal development
---

```{=html}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="../../index.html">Home</a></li>
    <li class="breadcrumb-item"><a href="../../publications.html">Publications</a></li>
  </ol>
</nav>
```

## Citation (APA 7)

> Oller, D. K., Ramsay, G., Bene, E., Long, H. L., & Griebel, U. (2021). Protophones, the precursors to speech, dominate the human infant vocal landscape. *Philosophical Transactions of the Royal Society B: Biological Sciences*, *376*(1836), 20200255. <https://doi.org/10.1098/rstb.2020.0255>

## Abstract

Human infant vocalization is viewed as a critical foundation for vocal learning and language. All apes share distress sounds (shrieks and cries) and laughter. Another vocal type, speech-like sounds, common in human infants, is rare but not absent in other apes. These three vocal types form a basis for especially informative cross-species comparisons. To make such comparisons possible we need empirical research documenting the frequency of occurrence of all three. The present work provides a comprehensive portrayal of these three vocal types in the human infant from longitudinal research in various circumstances of recording. Recently, the predominant vocalizations of the human infant have been shown to be speech-like sounds, or 'protophones', including both canonical and non-canonical babbling. The research shows that protophones outnumber cries by a factor of at least five based on data from random-sampling of all-day recordings across the first year. The present work expands on the prior reports, showing the protophones vastly outnumber both cry and laughter in both all-day and laboratory recordings in various circumstances. The data provide new evidence of the predominance of protophones in the infant vocal landscape and illuminate their role in human vocal learning and the origin of language. This article is part of the theme issue 'Vocal learning in animals and humans'.
