---
title: "Marginal and canonical babbling in 10 infants at risk for cerebral palsy"
type: "article"
author: "Long & Hustad"
year: "2023"
publication: "American Journal of Speech-Language Pathology"
doi: "https://doi.org/10.1044/2022_AJSLP-22-00165"
pubmed: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10561958/"
toc: false
categories:
  - infant
  - vocal development
  - cerebral palsy
---

```{=html}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="../../index.html">Home</a></li>
    <li class="breadcrumb-item"><a href="../../publications.html">Publications</a></li>
  </ol>
</nav>
```

## Citation (APA 7)

> Long, H. L., & Hustad, K. C. (2023). Marginal and canonical babbling in 10 infants at risk for cerebral palsy. *American Journal of Speech-Language Pathology*, *32*(4S), 1835--1849. <https://doi.org/10.1044/2022_AJSLP-22-00165>

## Abstract

Purpose: This study is a preliminary quantification and characterization of the development of marginal and canonical syllable patterns in 10 infants at risk for cerebral palsy (CP).

Method: We calculated marginal and canonical babbling ratios from parentinfant laboratory recordings of 10 infants at two time points, approximately 13 and 16 months of age. The frequency and diversity of labial, coronal, and velar types of marginal and canonical syllables were also examined. Differences across three outcome groups were compared: infants later diagnosed with CP (n = 3, CP group), risk of CP due to ongoing gross motor delays (n = 4, risk group), and current typically developing status with resolved gross motor delays (n = 3, TDx group). Performance on the Mullen Scales was included for perspective on cognitive development.

Results: Higher marginal syllable ratios were observed in the CP and risk groups than the TDx group. An increasing canonical syllable ratio across the two ages was consistently observed in the TDx group. The TDx group produced a greater frequency and diversity of canonical syllable types than the risk and CP groups, and of marginal syllable types than the CP group.

Conclusions: This study offers preliminary support for the possibility that speech motor impairment in infants with CP have the potential to be observed and quantified early in vocal development prior to the expected onset of first words. Prolonged rates of marginal syllable forms may be suggestive of speech motor impairment; however, additional longitudinal outcome data over a longer time course and a larger sample of infants are needed to provide further support for this possibility.
