---
title: "The effect of open access on scholarly and societal metrics of impact in the ASHA Journals"
type: "article"
author: "Long, Drown, & El Amin"
year: "2023"
publication: "Journal of Speech, Language, and Hearing Research"
doi: "https://doi.org/10.1044/2022_JSLHR-22-00315"
postprint: "https://osf.io/preprints/osf/2ufte_v1"
materials: "https://osf.io/927bk/"
toc: false
categories:
  - open science
---

```{=html}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="../../index.html">Home</a></li>
    <li class="breadcrumb-item"><a href="../../publications.html">Publications</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{< meta title >}}</li>
  </ol>
</nav>
```

## Citation (APA 7)

> Long, H. L., Drown, L., & El Amin, M. (2023). The effect of open access on scholarly and societal metrics of impact in the ASHA Journals. *Journal of Speech, Language, and Hearing Research*, *66*(6), 1948--1957. <https://doi.org/10.1044/2022_JSLHR-22-00315>

## Abstract

Purpose: This study examined the effect of open access (OA) status on scholarly and societal metrics of impact (citation counts and altmetric scores, respectively) across manuscripts published in the American Speech-Language-Hearing Association (ASHA) Journals.

Method: Three thousand four hundred nineteen manuscripts published in four active ASHA Journals were grouped across three access statuses based on their availability to the public: Gold OA, Green OA, and Closed Access. Two linear mixed-effects models tested the effects of OA status on citation counts and altmetric scores of the manuscripts.

Results: Both Green OA and Gold OA significantly predicted a 2.70 and 5.21 respective increase in citation counts compared with Closed Access manuscripts (p \< .001). Gold OA was estimated to predict a 25.7-point significant increase in altmetric scores (p \< .001), but Green OA was only marginally significant (p = .68) in predicting a 1.44 increase in altmetric scores relative to Closed Access manuscripts.

Discussion: Communication sciences and disorders (CSD) research that is fully open receives more online attention and, overall, more scientific attention than research that is paywalled or available through Green OA methods. Additional research is needed to understand secondary variables affecting these and other scholarly and societal metrics of impact across studies in CSD. Ongoing support and incentives to reduce the inequities of OA publishing are critical for continued scientific advancement.
