---
title: "Vocal characteristics of infants at risk for speech motor involvement: A scoping review"
type: "article"
author: "Long, Christensen, Hayes, & Hustad"
year: "2023"
publication: "Journal of Speech, Language, and Hearing Research"
doi: "https://doi.org/10.1044/2023_JSLHR-23-00336"
postprint: "https://osf.io/preprints/osf/u6m9n_v1" 
materials: "https://osf.io/jf3u6/"
toc: false
categories:
  - infant
  - vocal development
  - cerebral palsy
---

```{=html}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="../../index.html">Home</a></li>
    <li class="breadcrumb-item"><a href="../../publications.html">Publications</a></li>
  </ol>
</nav>
```

## Citation (APA 7)

> Long, H. L., Christensen, L., Hayes, S., & Hustad, K. C. (2023). Vocal characteristics of infants at risk for speech motor involvement: A scoping review. *Journal of Speech, Language, and Hearing Research*, *66*(11), 4432--4460. <https://doi.org/10.1044/2023_JSLHR-23-00336>

## Abstract

Purpose: The purpose of this scoping review was to (a) summarize methodological characteristics of studies examining vocal characteristics of infants at high risk for neurological speech motor involvement and (b) report the state of the high-quality evidence on vocal characteristic trends of infants diagnosed or at high risk for cerebral palsy (CP).

Method: The PRISMA (Preferred Reporting Items of Systematic Reviews and Meta-Analyses) extension for scoping reviews was followed for reporting our review. Studies measured prelinguistic vocal characteristics of infants under 24 months with birth risk or genetic conditions known to commonly present with speech motor involvement. Fifty-five studies met criteria for Part 1. Eleven studies met criteria for synthesis in Part 2.

Results: A smaller percentage of studies examined infants with or at risk for CP compared to studies examining genetic conditions such as Down syndrome. The median year of publication was 1999, with a median sample size of nine participants. Most studies were conducted in laboratory settings and used human coding of vocalizations produced during caregiver--child interactions. Substantial methodological differences were noted across all studies. A small number of high-quality studies of infants with or at risk for CP revealed high rates of marginal babbling, low rates of canonical babbling, and limited consonant diversity under 24 months. Mixed findings were noted across studies of general birth risk factors.

Conclusions: There is limited evidence available to support the early detection of speech motor involvement. Large methodological differences currently impact the ability to synthesize findings across studies. There is a critical need to conduct longitudinal research with larger sample sizes and advanced, modern technologies to detect vocal precursors of speech impairment to support the accurate diagnosis and prognosis of speech development in infants with CP and other clinical populations.
