---
title: "Open science practices in communication sciences and disorders: A survey"
type: "article"
author: "El Amin, Borders, Long, Keller, & Kearney"
year: "2023"
publication: "Journal of Speech, Language, and Hearing Research"
doi: "https://doi.org/10.1044/2022_JSLHR-22-00062"
postprint: "https://osf.io/preprints/osf/jwba3_v1"
materials: "https://osf.io/2f7xp/"
toc: false
categories:
  - open science
---

```{=html}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="../../index.html">Home</a></li>
    <li class="breadcrumb-item"><a href="../../publications.html">Publications</a></li>
  </ol>
</nav>
```


> El Amin, M., Borders, J. C., Long, H. L., Keller, M. A., & Kearney, E. (2023). Open science practices in communication sciences and disorders: A survey. *Journal of Speech, Language, and Hearing Research*, *66*(6), 1928--1947. <https://doi.org/10.1044/2022_JSLHR-22-00062>

# Abstract

Purpose: Open science is a collection of practices that seek to improve the accessibility, transparency, and replicability of science. Although these practices have garnered interest in related fields, it remains unclear whether open science practices have been adopted in the field of communication sciences and disorders (CSD). This study aimed to survey the knowledge, implementation, and perceived benefits and barriers of open science practices in CSD.

Method: An online survey was disseminated to researchers in the United States actively engaged in CSD research. Four-core open science practices were examined: preregistration, self-archiving, gold open access, and open data. Data were analyzed using descriptive statistics and regression models.

Results: Two hundred twenty-two participants met the inclusion criteria. Most participants were doctoral students (38%) or assistant professors (24%) at R1 institutions (58%). Participants reported low knowledge of preregistration and gold open access. There was, however, a high level of desire to learn more for all practices. Implementation of open science practices was also low, most notably for preregistration, gold open access, and open data (\< 25%). Predictors of knowledge and participation, as well as perceived barriers to implementation, are discussed.

Conclusion: Although participation in open science appears low in the field of CSD, participants expressed a strong desire to learn more in order to engage in these practices in the future.
