---
title: "Acoustic features of vocalizations in typically developing and autistic infants in the first year"
type: "article"
author: "Oller, Bene, Yoo, Su, Long, Klaiman, Pulver, Richardson, Pileggi, Brane, & Ramsay"
year: "2024"
publication: "Research in Developmental Disabilities"
doi: "https://doi.org/10.1016/j.ridd.2024.104849"
pubmed: "https://pubmed.ncbi.nlm.nih.gov/39413560/"
toc: false
categories:
  - infant
  - vocal development
  - autism
---

```{=html}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="../../index.html">Home</a></li>
    <li class="breadcrumb-item"><a href="../../publications.html">Publications</a></li>
  </ol>
</nav>
```


> Oller, D. K., Bene, E. R., Yoo, H., Su, P. L., Long, H. L., Klaiman, C., Pulver, S. L., Richardson, S., Pileggi, M. L., Brane, N., & Ramsay, G. (2024). Acoustic features of vocalizations in typically developing and autistic infants in the first year. *Research in Developmental Disabilities*, *154*(1), 104849. <https://doi.org/10.1016/j.ridd.2024.104849>

# Abstract

Background: We describe acoustic patterns across the five most prominent vocal types in typically developing infants (TD) and compare them with patterns in infants who develop autism (ASD) or a developmental disability (DD) not related to autism. Infant-directed speech (IDS) is a potentially important influence on such vocal acoustic patterns. Both acoustic patterns and effects of IDS are important for understanding the earliest origins of communication disorders.

Aims: To compare duration, pitch and loudness of infant vocalizations for three groups of infants (TD, ASD, DD) in circumstances with high or low amounts of IDS.

Methods and Procedures: Two five-minute segments from each of 1259 all-day recordings across the first year were coded and acoustically analyzed for three groups of infants (130 TD, 44 ASD, 21 DD). Duration, mean fundamental frequency, and root mean square amplitude were determined for \>162,000 infant utterances.

Outcomes and Results: Cries were longest and loudest, and vowel-like sounds were shortest of the five vocal types in all groups. TD infants showed significant alterations in vocal acoustics during periods of high IDS.

Conclusions and Implications: Strong similarities in acoustic patterns occurred across the three groups, but only the TD group showed significant acoustic effects of IDS.
