---
title: "Canonical babbling trajectories across the first year of life in autism and typical development"
type: "article"
author: "Long, Ramsay, Bene, Su, Yoo, Klaiman, Pulver, Richardson, Pileggi, Brane, & Oller"
year: "2024"
publication: "Autism"
doi: "https://doi.org/10.1177/13623613241253908"
postprint: "https://osf.io/preprints/osf/2h437_v1"
materials: "https://osf.io/zea63/"
toc: false
categories:
  - infant
  - vocal development
  - autism
---

```{=html}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="../../index.html">Home</a></li>
    <li class="breadcrumb-item"><a href="../../publications.html">Publications</a></li>
  </ol>
</nav>
```


> Long, H. L., Ramsay, G., Bene, E. R., Su, P. L., Yoo, H., Klaiman, C., Pulver, S. L., Richardson, S., Pileggi, M. L., Brane, N., & Oller, D. K. (2024). Canonical babbling trajectories across the first year of life in autism and typical development. *Autism*, *28*(12), 3078--3091. <https://doi.org/10.1177/13623613241253908>

# Abstract

This study explores vocal development as an early marker of autism, focusing on canonical babbling rate and onset, typically established by 7 months. Previous reports suggested delayed or reduced canonical babbling in infants later diagnosed with autism, but the story may be complicated. We present a prospective study on 44 infants later diagnosed with autism spectrum disorder compared with 127 infants later identified as typically developing who were followed longitudinally with day-long recordings from 0 to 13 months. Eight 5-min segments from each of their recordings were coded for canonical and noncanonical syllables. The results confirmed many reports that canonical babbling is a robust feature of human vocal development in the first year of life, with small overall mean differences in canonical babbling rates between the autism spectrum disorder and typically developing groups beginning around 9 months, primarily in males. Our findings highlight the importance of considering sex differences in vocal communication as part of the early detection and diagnosis of autism when determining the need for communication supports to maximize outcomes.
