---
title: "Foundations of vocal category development in autistic infants"
type: "article"
author: "Su, Yoo, Ramsay, Long, Bene, Klaiman, Pulver, Richardson, Pileggi, Brane, & Oller"
year: "2024"
publication: "Journal of Autism and Developmental Disorders"
doi: "https://doi.org/10.1007/s10803-024-06267-9"
pubmed: "https://pubmed.ncbi.nlm.nih.gov/38403868/"
toc: false
categories:
  - infant
  - vocal development
  - autism
---

```{=html}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="../../index.html">Home</a></li>
    <li class="breadcrumb-item"><a href="../../publications.html">Publications</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{< meta title >}}</li>
  </ol>
</nav>
```

## Citation (APA 7)

> Su, P. L., Yoo, H., Ramsay, G., Long, H. L., Bene, E. R., Klaiman, C., Pulver, S. L., Richardson, S., Pileggi, M. L., Brane, N., & Oller, D. K. (2024). Foundations of vocal category development in autistic infants. *Journal of Autism and Developmental Disorders*. <https://doi.org/10.1007/s10803-024-06267-9>

## Abstract

The present study compared the infant's tendency in the first year of life to produce clusters of particular vocal types (squeals, vocants, and growls) in typically developing (TD) and autistic infants. Vocal clustering provides evidence of vocal category formation and may establish a foundation for speech development. Specifically, we compared the extent of vocal clustering across outcome groups and age groups. We also examined the associations between the extent of vocal clustering and later outcomes at 2 years within the autistic group. Randomly selected 5-min segments (27,153 5-min segments total) from 1293 all-day home recordings from 103 TD infants and 44 autistic infants across the first year were humancoded (about 9.75 h of data coded per infant on average) to derive vocal clustering patterns. Fisher's exact tests were used to compare the occurrence of squeals versus vocants, as well as growls versus vocants, across coded segments. Infants in both groups demonstrated clear clustering patterns of squeals and growls across all age groups. The extent of vocal clustering in the autistic group did not correlate significantly with later language, repetitive behavior, or autism severity outcomes. These findings highlight the robustness of the systematic production of vocal categories across the first year of life. The similarity of the clustering patterns in the TD and autistic groups suggests that vocal category formation through active infant vocal exploration is a robust feature of early speech development.
