---
title: "Infant vocal category exploration as a foundation for speech development"
type: "article"
author: "Yoo, Su, Ramsay, Long, Bene, & Oller"
year: "2024"
publication: "PLOS ONE"
doi: "https://doi.org/10.1371/journal.pone.0299140"
oa: "https://doi.org/10.1371/journal.pone.0299140"
toc: false
categories:
  - infant
  - vocal development
---

```{=html}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="../../index.html">Home</a></li>
    <li class="breadcrumb-item"><a href="../../publications.html">Publications</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{< meta title >}}</li>
  </ol>
</nav>
```

## Citation (APA 7)

> Yoo, H., Su, P. L., Ramsay, G., Long, H. L., Bene, E. R., & Oller, D. K. (2024). Infant vocal category exploration as a foundation for speech development. *PLOS ONE*, *19*(5), e0299140. <https://doi.org/10.1371/journal.pone.0299140>

## Abstract

Non-random exploration of infant speech-like vocalizations (e.g., squeals, growls, and vowel-like sounds or "vocants") is pivotal in speech development. This type of vocal exploration, often noticed when infants produce particular vocal types in clusters, serves two crucial purposes: it establishes a foundation for speech because speech requires formation of new vocal categories, and it serves as a basis for vocal signaling of wellness and interaction with caregivers. Despite the significance of clustering, existing research has largely relied on subjective descriptions and anecdotal observations regarding early vocal category formation. In this study, we aim to address this gap by presenting the first large-scale empirical evidence of vocal category exploration and clustering throughout the first year of life. We observed infant vocalizations longitudinally using all-day home recordings from 130 typically developing infants across the entire first year of life. To identify clustering patterns, we conducted Fisher's exact tests to compare the occurrence of squeals versus vocants, as well as growls versus vocants. We found that across the first year, infants demonstrated clear clustering patterns of squeals and growls, indicating that these categories were not randomly produced, but rather, it seemed, infants actively engaged in practice of these specific categories. The findings lend support to the concept of infants as manifesting active vocal exploration and category formation, a key foundation for vocal language.
