---
title: "“There’s going to have to be a culture shift”: Associate and full professors’ perceptions and experiences related to open science practices in communication sciences and disorders."
type: "article"
author: "Pfeiffer, Thompson, Baron, Brice, Ciullo, Hirsch, Long, & Ford"
year: "under review"
publication: "EdArXiv Preprints"
preprint: "https://doi.org/10.35542/osf.io/ygfhp_v1"
materials: "https://osf.io/dvkqg/"
preregistration: "https://osf.io/he3np"
toc: false
categories:
  - open science
---

```{=html}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="../../index.html">Home</a></li>
    <li class="breadcrumb-item"><a href="../../publications.html">Publications</a></li>
  </ol>
</nav>
```


> Pfeiffer, DL, Thompson, A, Baron, A, Brice, C, Ciullo, B, Hirsch, ME, Long, HL, & Ford, A (under review). “There’s going to have to be a culture shift”: Associate and full professors’ perceptions and experiences related to open science practices in communication sciences and disorders. *EdArXiv Preprints.*

# Abstract

Purpose: The purpose of this qualitative study is to expand upon the findings of Pfeiffer et al.’s (2025) study of the perceptions and experiences of Assistant Professors in Communication Sciences and Disorders (CSD) related to open science (OS) by examining those of Associate and Full Professors. 
Method: Thirty-one faculty in CSD (15 Associate Professors and 16 Full Professors) each participated in one 1-hour virtual focus group conducted via Zoom videoconferencing software. The researchers used both deductive and inductive coding methods to analyze the focus group data and develop categories and subcategories summarizing the discussions.
Results: The researchers developed five categories to summarize the focus group discussions: (1) a desire to learn more about various OS practices and how to implement them by learning with and from others through a variety of formats; (2) OS practices have the potential to positively impact their research process and products, their careers, and the research communities they serve (e.g., clinicians, clinical populations); (3) OS practices could enhance the quality and credibility of research in CSD and reduce the research-to-practice gap by engaging both clinicians and researchers; (4) identification of both individual-level and systemic-level factors that could act as barriers or serve as facilitators to their use of OS practices; and (5) recommendations for a cultural shift to reduce barriers to engage in OS practices in CSD. 
Conclusions: Associate and Full Professors in CSD perceive many of the same barriers and facilitators to engaging in open science as Assistant Professors; however, they uniquely highlighted the need for a cultural shift from the ways they were trained to enhance implementation of OS practices. This shift includes embedding education about OS early in academic training, clearly outlining benefits and incentives for engaging in OS, and providing opportunities for clinicians to partner with researchers in learning about and implementing these practices.
