---
title: "Canonical Babbling Development in Infancy: A Systematic Review and Meta-Analysis of Methodological and Ambient Language Influences"
type: "article"
author: "Cychosz & Long"
year: "under review"
publication: "OSFPreprints"
preprint: "https://osf.io/preprints/osf/8ub2v_v1"
materials: "https://osf.io/tks5h/"
toc: false
categories:
  - infant
  - vocal development
---

```{=html}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="../../index.html">Home</a></li>
    <li class="breadcrumb-item"><a href="../../publications.html">Publications</a></li>
  </ol>
</nav>
```


> Cychosz, M., & Long, H. L. (under review). Canonical babbling development in infancy: A systematic review and meta-analysis of methodological and ambient language influences. *OSFPreprints.* https://doi.org/10.31219/osf.io/8ub2v_v1


# Abstract

Canonical babbling, or the production of adult-like consonant-vowel syllables in infancy, represents a critical milestone in pre-linguistic vocal development and predicts later speech and language outcomes. This systematic review and meta-analysis synthesized findings from 43 studies and 1,291 infants aged 5-24 months across 16 language environments to examine how methodological and contextual factors influence the most common measure of canonical babbling: the canonical babbling ratio (CBR). Results confirmed a robust, linear increase in CBR with age, reinforcing its role as a consistent developmental marker. Different CBR measures yielded comparable developmental trajectories. Sampling method significantly affected CBR values, with interactive free play sessions eliciting higher CBRs than naturalistic home recordings, particularly in older infants. In contrast, the location of data collection had no effect. Ambient language complexity also shaped CBR: infants acquiring languages with more complex syllable structures (e.g., English, Dutch) initially exhibited lower CBRs compared to infants acquiring languages with less complex syllable structures (e.g., Mandarin, Spanish). Despite these initial differences, babbling trajectories were predicted to converge by approximately 21 months as infants exposed to languages with more complex syllables demonstrated accelerated CBR growth. Publication bias was detected, with smaller samples more likely to report inflated CBRs. To address this issue, simulation-based analyses are reported to estimate sample size recommendations for improved precision in future research. Together, these results support CBR as a meaningful developmental marker while offering practical guidance for future research directions and continued clinical applications.

